# Taken from roblox-ts: https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml under MIT license
name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_C1494E503995F49DA6AB87DF26BA38EEEC1B8F1D2AA7E69EB1DCA5693BB9F2079006CDC9698C8359483E2D25343EE0D1BE55F47EA0597A6C6492E09B7755CBBF5A6C2C9599871E51BFCCCF719109CB08A339502B5A6C62F1C9EC48B19E6B5177CFA49291858372E75DE48D72AAC7E82E7C6EB8F6696D5D7154FACF6BB443D8550AEAD830CE83E5FC8CBD996352BBFE36AD12B9B7F84724348AA1CDC213A90CFC615A2C49B02EFEFC4A4AFB42919716FB972B8CBBA0BDADF82E0CCA9D647D705EAB3F8971D993409E41A60AEFCBDBD59446349B9647ACCF6602D4BA35F3ABA9CFD783DDA47794489AA24D44C21DABDC80B031D68BA776591F87B45FFF8B50F14F709876F2435BBC570B9BA280C7240F7985AB910B5AD4795139B40FC86E5603AAEBC887537E2AD5D3959EACDF3EDE4D801108A6B5F7CDE22F87C7A74F0B08F9D19CE5E8B440A59E1FBE70D4B08572338A20ECB3065625DDECFFC512E2A2A3C59C1E6F43A6D2BD86DFD9B2EB45E4FB96F489A0EC22F881D5DD86D0A19C0BD0EFB62C224942ED7EC6C3726350D156546009F0D22376' }}

jobs:
  unit-tests:
    if: contains(github.event.commits[0].message, '[actions]') == false
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Download OpenVPN
        run: choco install openvpn

      - name: Run OpenVPN
        run: Start-Process -FilePath "C:\\Program Files\\OpenVPN\\bin\\openvpn.exe" -ArgumentList "--config $((Resolve-Path .\\actions.ovpn).Path)"

      - name: Poll for IP Change
        run: |
          $elapsed = 0
          while ($true) {
            try {
              $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
              $content = ConvertFrom-Json $response.Content
              if ($content.origin -eq "159.223.100.103") {
                break
              }
            } catch {}
            if ($elapsed -ge 20) {
              Write-Error "Timeout reached!"
              exit 1
            }
            Write-Output "Polling.. Elasped: $elapsed, IP: $($content.origin)"
            Start-Sleep 5
            $elapsed += 5
          }
          Write-Output "Success!"

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ env.ROBLOSECURITY }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile and run tests
        run: npm test
        
      - name: Screenshot
        if: failure()
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'
