# Taken from roblox-ts: https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml under MIT license
name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}

jobs:
  unit-tests:
    if: contains(github.event.commits[0].message, '[actions]') == false
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Download WireGuard
        run: Invoke-WebRequest -Uri https://download.wireguard.com/windows-client/wireguard-installer.exe -OutFile ./wireguard-installer.exe;

      - name: Install WireGuard
        run: ./wireguard-installer.exe

      - name: Wait for WireGuard Installer?
        run: while (!(Test-Path 'C:\\Program Files\\WireGuard\\wireguard.exe')) { Start-Sleep 5 }

      - name: Run WireGuard
        run: "& \"C:\\Program Files\\WireGuard\\wireguard.exe\" /installtunnelservice $((Resolve-Path .\\wireguard.conf).Path)"

      - name: Poll for IP Change
        run: |
          $elapsed = 0
          while ($true) {
            try {
              $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
              $content = ConvertFrom-Json $response.Content
              if ($content.origin -eq "159.223.100.103") {
                break
              }
            } catch {}
            if ($elapsed -ge 20) {
              Write-Error "Timeout reached!"
              exit 1
            }
            Write-Output "Polling.. Elasped: $elapsed, IP: $($content.origin)"
            Start-Sleep 5
            $elapsed += 5
          }
          Write-Output "Success!"

      - name: Validate Cookie
        run: |
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
          $cookie = New-Object System.Net.Cookie
          $cookie.Name = ".ROBLOSECURITY"
          $cookie.Value = "${{ env.ROBLOSECURITY }}"
          $cookie.Domain = ".roblox.com"
          $session.Cookies.Add($cookie);
          Invoke-WebRequest "https://avatar.roblox.com/v1/avatar" -WebSession $session -UseBasicParsing

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ env.ROBLOSECURITY }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile and run tests
        run: npm test
        
      - name: Screenshot
        if: failure()
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'
