# Taken from roblox-ts: https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml under MIT license
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile and run tests
        run: npm test
